// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

// Run with: go run ./examples/webhook_endpoints
package main

import (
	"context"
	"encoding/json"
	"fmt"

	parceleventsnightly "github.com/sdk-fixture-lab-260904/parcel-events-nightly-go"
)

func main() {
	ctx := context.Background()
	client := parceleventsnightly.NewClient(parceleventsnightly.WithAPIKey("my-api-key"))

	var body parceleventsnightly.CreateWebhookEndpointRequest
	if err := json.Unmarshal([]byte("{\"description\":\"string\",\"events\":[\"pickup.completed\"],\"url\":\"https://hooks.parcel-events.example/events\"}"), &body); err != nil {
		panic(err)
	}
	result, err := client.WebhookEndpoints.Create(ctx, body)
	if err != nil {
		panic(err)
	}
	fmt.Println(result)
}
