// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

package parceleventsnightly

import (
	"context"
	"net/http"
	"os"
	"time"

	"github.com/sdk-fixture-lab-260904/parcel-events-nightly-go/kernel"
)

// defaultTimeout is the IR-frozen `timeouts.default_ms`.
const defaultTimeout = 45000 * time.Millisecond

type clientConfig struct {
	baseURL string

	httpClient *http.Client

	timeout time.Duration

	retries *kernel.RetryPolicy

	validation bool

	headers [][2]string

	auth map[string]kernel.AuthProvider
}

// WithValidation controls structural request and response checks (enabled by default).
func WithValidation(enabled bool) Option {
	return func(c *clientConfig) { c.validation = enabled }
}

// Option configures NewClient (the functional options pattern).
type Option func(*clientConfig)

// WithBaseURL overrides the base URL.
func WithBaseURL(baseURL string) Option {
	return func(c *clientConfig) { c.baseURL = baseURL }
}

// WithHTTPClient swaps the underlying *http.Client.
func WithHTTPClient(httpClient *http.Client) Option {
	return func(c *clientConfig) { c.httpClient = httpClient }
}

// WithTimeout sets the default per-request timeout.
func WithTimeout(timeout time.Duration) Option {
	return func(c *clientConfig) { c.timeout = timeout }
}

// WithRetryPolicy replaces the retry policy (start from
// kernel.DefaultRetryPolicy or the SDK default).
func WithRetryPolicy(policy kernel.RetryPolicy) Option {
	return func(c *clientConfig) { c.retries = &policy }
}

// WithDefaultHeader stamps a header onto every request.
func WithDefaultHeader(name string, value string) Option {
	return func(c *clientConfig) { c.headers = append(c.headers, [2]string{name, value}) }
}

// Environment names a configured base URL.
type Environment string

// EnvironmentProduction is the `production` environment.
const EnvironmentProduction Environment = "production"

// EnvironmentSandbox is the `sandbox` environment.
const EnvironmentSandbox Environment = "sandbox"

// Environments maps every configured environment to its base URL.
var Environments = map[Environment]string{EnvironmentProduction: "https://api.parcel-events.example", EnvironmentSandbox: "https://sandbox.parcel-events.example"}

// WithEnvironment selects a configured environment.
func WithEnvironment(environment Environment) Option {
	return func(c *clientConfig) {
		if baseURL, ok := Environments[environment]; ok {
			c.baseURL = baseURL
		}
	}
}

// WithAPIKey authenticates the `api_key` scheme with a static API key (header `Parcel-API-Key`).
func WithAPIKey(key string) Option {
	return func(c *clientConfig) {
		c.auth["api_key"] = kernel.APIKeyAuth(kernel.APIKeyInHeader, "Parcel-API-Key", key)
	}
}

// WithBearerToken authenticates the `bearer_token` scheme with a static bearer token.
func WithBearerToken(key string) Option {
	return func(c *clientConfig) {
		c.auth["bearer_token"] = kernel.BearerAuth(key)
	}
}

// authGroups is the config's anyOf resolution order (first satisfied wins).
var authGroups = [][]string{{"api_key"}, {"bearer_token"}}

func resolveAuth(configured map[string]kernel.AuthProvider) kernel.AuthProvider {
	providers := make(map[string]kernel.AuthProvider, len(configured))
	for name, provider := range configured {
		providers[name] = provider
	}
	if providers["api_key"] == nil {
		if value := os.Getenv("PARCEL_EVENTS_API_KEY"); value != "" {
			providers["api_key"] = kernel.APIKeyAuth(kernel.APIKeyInHeader, "Parcel-API-Key", value)
		}
	}
	if providers["bearer_token"] == nil {
		if value := os.Getenv("PARCEL_EVENTS_BEARER_TOKEN"); value != "" {
			providers["bearer_token"] = kernel.BearerAuth(value)
		}
	}
	for _, group := range authGroups {
		selected := make([]kernel.AuthProvider, 0, len(group))
		for _, name := range group {
			if providers[name] == nil {
				break
			}
			selected = append(selected, providers[name])
		}
		if len(selected) != len(group) {
			continue
		}
		return selected[0]
	}
	return nil
}

// defaultRetryPolicy is the IR-frozen `retries:` configuration.
func defaultRetryPolicy() kernel.RetryPolicy {
	policy := kernel.DefaultRetryPolicy()
	policy.Enabled = true
	policy.MaxRetries = 3
	policy.InitialDelay = 250 * time.Millisecond
	policy.MaxDelay = 8000 * time.Millisecond
	policy.MaxElapsed = 60000 * time.Millisecond
	policy.Exponent = 2
	policy.StatusCodes = []kernel.StatusMatcher{"408", "409", "429", "5XX"}
	policy.RetryConnectionErrors = true
	return policy
}

// core is the shared transport seam: kernel calls + error remapping.
type core struct {
	kernel *kernel.Client
}

func (c *core) do(ctx context.Context, method string, path string, options ...kernel.RequestOption) (*kernel.Response, error) {
	response, err := c.kernel.Do(ctx, method, path, options...)
	if err != nil {
		return nil, remapError(err)
	}
	return response, nil
}

// RequestPage implements kernel.PageFetcher (with error remapping).
func (c *core) RequestPage(ctx context.Context, request kernel.PageRequest) (any, error) {
	data, err := c.kernel.RequestPage(ctx, request)
	if err != nil {
		return nil, remapError(err)
	}
	return data, nil
}

// Client is the github.com/sdk-fixture-lab-260904/parcel-events-nightly-go API client. Construct with NewClient.
type Client struct {
	core *core

	Labels *LabelsService

	Pickups *PickupsService

	Rates *RatesService

	Shipments *ShipmentsService

	Tracking *TrackingService

	WebhookEndpoints *WebhookEndpointsService
}

// NewClient builds a github.com/sdk-fixture-lab-260904/parcel-events-nightly-go client (functional options).
func NewClient(options ...Option) *Client {
	config := clientConfig{validation: true}
	config.baseURL = Environments[EnvironmentProduction]
	config.timeout = defaultTimeout
	config.auth = map[string]kernel.AuthProvider{}
	for _, option := range options {
		option(&config)
	}
	kernelOptions := make([]kernel.ClientOption, 0, 8)
	kernelOptions = append(kernelOptions, kernel.WithSDKIdentity("github.com/sdk-fixture-lab-260904/parcel-events-nightly-go", "0.1.0+sdk.86f765976c3b"))
	kernelOptions = append(kernelOptions, kernel.WithTimeout(config.timeout))
	kernelOptions = append(kernelOptions, kernel.WithValidation(config.validation))
	if config.retries != nil {
		kernelOptions = append(kernelOptions, kernel.WithRetryPolicy(*config.retries))
	} else {
		kernelOptions = append(kernelOptions, kernel.WithRetryPolicy(defaultRetryPolicy()))
	}
	if config.httpClient != nil {
		kernelOptions = append(kernelOptions, kernel.WithHTTPClient(config.httpClient))
	}
	for _, header := range config.headers {
		kernelOptions = append(kernelOptions, kernel.WithDefaultHeader(header[0], header[1]))
	}
	kernelOptions = append(kernelOptions, kernel.WithIdempotency(kernel.IdempotencyConfig{Header: "Idempotency-Key", AutoGenerate: true}))
	if provider := resolveAuth(config.auth); provider != nil {
		kernelOptions = append(kernelOptions, kernel.WithAuth(provider))
	}
	c := &core{kernel: kernel.NewClient(config.baseURL, kernelOptions...)}
	client := &Client{core: c}
	client.Labels = newLabelsService(c)
	client.Pickups = newPickupsService(c)
	client.Rates = newRatesService(c)
	client.Shipments = newShipmentsService(c)
	client.Tracking = newTrackingService(c)
	client.WebhookEndpoints = newWebhookEndpointsService(c)
	return client
}

// Retrieve — Retrieve a public tracking timeline
//
// `GET /v1/tracking/{tracking_number}` (`retrieveTrackingTimeline`)
//
// `tracking.retrieve` attached to the client root (`$client: true`).
func (c *Client) Retrieve(ctx context.Context, trackingNumber string, opts ...kernel.RequestOption) (*TrackingTimeline, error) {
	return c.Tracking.Retrieve(ctx, trackingNumber, opts...)
}
