// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

package parceleventsnightly

import (
	"encoding/json"
	"fmt"
)

// decodeResponse decodes a parsed JSON body into T via a JSON round trip.
func decodeResponse[T any](data any) (T, error) {
	var out T
	raw, err := json.Marshal(data)
	if err != nil {
		return out, fmt.Errorf("encode response: %w", err)
	}
	if err := json.Unmarshal(raw, &out); err != nil {
		return out, fmt.Errorf("decode response: %w", err)
	}
	return out, nil
}
