// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

// Package parceleventsnightly is the github.com/sdk-fixture-lab-260904/parcel-events-nightly-go SDK, generated by the
// Doctorine SDK Foundry (sdkSha 59df13efa6be). Runtime dependencies:
// the Go standard library only — the HTTP kernel is vendored under kernel/.
package parceleventsnightly
