// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

package parceleventsnightly

import (
	"errors"

	"github.com/sdk-fixture-lab-260904/parcel-events-nightly-go/kernel"
)

// APIError is every non-2xx HTTP response (alias of the kernel type;
// reach it with errors.As, match families with errors.Is).
type APIError = kernel.APIError

// ConnectionError is a request that never produced an HTTP response
// (alias of the kernel type).
type ConnectionError = kernel.ConnectionError

// Status-family and connection sentinels (errors.Is), kernel re-exports.
var ErrBadRequest = kernel.ErrBadRequest
var ErrAuthentication = kernel.ErrAuthentication
var ErrPermissionDenied = kernel.ErrPermissionDenied
var ErrNotFound = kernel.ErrNotFound
var ErrConflict = kernel.ErrConflict
var ErrUnprocessableEntity = kernel.ErrUnprocessableEntity
var ErrRateLimit = kernel.ErrRateLimit
var ErrInternalServer = kernel.ErrInternalServer
var ErrConnection = kernel.ErrConnection
var ErrConnectionTimeout = kernel.ErrConnectionTimeout

// AuthenticationError is the configured error class for HTTP 401.
type AuthenticationError struct {
	*kernel.APIError
}

// Unwrap exposes the wrapped *kernel.APIError to errors.Is / errors.As.
func (e *AuthenticationError) Unwrap() error { return e.APIError }

// ConflictError is the configured error class for HTTP 409.
type ConflictError struct {
	*kernel.APIError
}

// Unwrap exposes the wrapped *kernel.APIError to errors.Is / errors.As.
func (e *ConflictError) Unwrap() error { return e.APIError }

// NotFoundError is the configured error class for HTTP 404.
type NotFoundError struct {
	*kernel.APIError
}

// Unwrap exposes the wrapped *kernel.APIError to errors.Is / errors.As.
func (e *NotFoundError) Unwrap() error { return e.APIError }

// PaymentRequiredError is the configured error class for HTTP 402.
type PaymentRequiredError struct {
	*kernel.APIError
}

// Unwrap exposes the wrapped *kernel.APIError to errors.Is / errors.As.
func (e *PaymentRequiredError) Unwrap() error { return e.APIError }

// RateLimitError is the configured error class for HTTP 429.
type RateLimitError struct {
	*kernel.APIError
}

// Unwrap exposes the wrapped *kernel.APIError to errors.Is / errors.As.
func (e *RateLimitError) Unwrap() error { return e.APIError }

// ServerError is the configured error class for HTTP 5XX.
type ServerError struct {
	*kernel.APIError
}

// Unwrap exposes the wrapped *kernel.APIError to errors.Is / errors.As.
func (e *ServerError) Unwrap() error { return e.APIError }

// ValidationError is the configured error class for HTTP 422 when `/type` = "https://parcel-events.example/problems/validation".
type ValidationError struct {
	*kernel.APIError
}

// Unwrap exposes the wrapped *kernel.APIError to errors.Is / errors.As.
func (e *ValidationError) Unwrap() error { return e.APIError }

// remapError re-types a kernel *APIError into the most specific
// configured error class (config order — the first match wins).
func remapError(err error) error {
	var apiErr *kernel.APIError
	if !errors.As(err, &apiErr) {
		return err
	}
	if matchStatuses(apiErr.Status, "401") {
		return &AuthenticationError{APIError: apiErr}
	}
	if matchStatuses(apiErr.Status, "409") {
		return &ConflictError{APIError: apiErr}
	}
	if matchStatuses(apiErr.Status, "404") {
		return &NotFoundError{APIError: apiErr}
	}
	if matchStatuses(apiErr.Status, "402") {
		return &PaymentRequiredError{APIError: apiErr}
	}
	if matchStatuses(apiErr.Status, "429") {
		return &RateLimitError{APIError: apiErr}
	}
	if matchStatuses(apiErr.Status, "5XX") {
		return &ServerError{APIError: apiErr}
	}
	if matchStatuses(apiErr.Status, "422") && bodyMatches(apiErr.Body, "$.type", "https://parcel-events.example/problems/validation") {
		return &ValidationError{APIError: apiErr}
	}
	return err
}

func matchStatuses(status int, matchers ...kernel.StatusMatcher) bool {
	for _, matcher := range matchers {
		if matcher.Matches(status) {
			return true
		}
	}
	return false
}

func bodyMatches(body any, pointer string, equals any) bool {
	value, err := kernel.ReadBodyPointer(body, pointer)
	if err != nil {
		return false
	}
	if equals == nil {
		return value != nil
	}
	return value == equals
}
