// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

package parceleventsnightly

import "encoding/json"

// Address — #/components/schemas/Address.
type Address struct {
	City string `json:"city"`

	Company *string `json:"company,omitempty"`

	Country string `json:"country"`

	Line1 string `json:"line1"`

	Line2 *string `json:"line2,omitempty"`

	Name string `json:"name"`

	Phone *string `json:"phone,omitempty"`

	PostalCode string `json:"postal_code"`

	Region *string `json:"region,omitempty"`
}

// CreateLabelRequest — #/components/schemas/CreateLabelRequest.
type CreateLabelRequest struct {
	Format LabelFormat `json:"format"`

	// Allowed: "a4", "letter", "four_by_six".
	PageSize *string `json:"page_size,omitempty"`

	ShipmentID string `json:"shipment_id"`
}

// CreatePickupRequest — #/components/schemas/CreatePickupRequest.
type CreatePickupRequest struct {
	Address *Address `json:"address"`

	Notes *string `json:"notes,omitempty"`

	ShipmentIds []string `json:"shipment_ids"`

	Window *PickupWindow `json:"window"`
}

// CreateShipmentRequest — #/components/schemas/CreateShipmentRequest.
type CreateShipmentRequest struct {
	DeliveryInstructions *string `json:"delivery_instructions,omitempty"`

	Metadata map[string]string `json:"metadata,omitempty"`

	Parcels []*Parcel `json:"parcels"`

	Recipient *Address `json:"recipient"`

	Reference string `json:"reference"`

	Sender *Address `json:"sender"`

	// Allowed: "economy", "express", "same_day".
	Service string `json:"service"`
}

// CreateWebhookEndpointRequest — #/components/schemas/CreateWebhookEndpointRequest.
type CreateWebhookEndpointRequest struct {
	Description *string `json:"description,omitempty"`

	Events []WebhookEventType `json:"events"`

	URL string `json:"url"`
}

// Label — #/components/schemas/Label.
type Label struct {
	DownloadURL string `json:"download_url"`

	ExpiresAt string `json:"expires_at"`

	Format LabelFormat `json:"format"`

	ID string `json:"id"`

	// Allowed: "label".
	Object string `json:"object"`

	Price *Money `json:"price"`

	ShipmentID string `json:"shipment_id"`
}

// LabelFormat — #/components/schemas/LabelFormat. Allowed: "pdf", "png", "zpl".
type LabelFormat = string

// Money — #/components/schemas/Money.
type Money struct {
	Amount string `json:"amount"`

	Currency string `json:"currency"`
}

// Parcel — #/components/schemas/Parcel.
type Parcel struct {
	Contents []*ParcelItem `json:"contents,omitempty"`

	HeightCm float64 `json:"height_cm"`

	LengthCm float64 `json:"length_cm"`

	WeightGrams int64 `json:"weight_grams"`

	WidthCm float64 `json:"width_cm"`
}

// ParcelItem — #/components/schemas/ParcelItem.
type ParcelItem struct {
	CustomsCode *string `json:"customs_code,omitempty"`

	Description string `json:"description"`

	Quantity int64 `json:"quantity"`

	UnitValue *Money `json:"unit_value"`
}

// Pickup — #/components/schemas/Pickup.
type Pickup struct {
	Address *Address `json:"address"`

	CreatedAt string `json:"created_at"`

	ID string `json:"id"`

	// Allowed: "pickup".
	Object string `json:"object"`

	ShipmentIds []string `json:"shipment_ids"`

	// Allowed: "scheduled", "completed", "canceled", "missed".
	Status string `json:"status"`

	Window *PickupWindow `json:"window"`
}

// PickupPage — #/components/schemas/PickupPage.
type PickupPage struct {
	Data []*Pickup `json:"data"`

	HasMore bool `json:"has_more"`

	NextCursor *string `json:"next_cursor"`
}

// PickupWindow — #/components/schemas/PickupWindow.
type PickupWindow struct {
	EndsAt string `json:"ends_at"`

	StartsAt string `json:"starts_at"`
}

// RateQuote — #/components/schemas/RateQuote.
type RateQuote struct {
	Amount *Money `json:"amount"`

	Carrier string `json:"carrier"`

	EstimatedDeliveryDate string `json:"estimated_delivery_date"`

	ExpiresAt string `json:"expires_at"`

	ID string `json:"id"`

	Service string `json:"service"`
}

// RateQuoteRequest — #/components/schemas/RateQuoteRequest.
type RateQuoteRequest struct {
	Parcels []*Parcel `json:"parcels"`

	Recipient *Address `json:"recipient"`

	Sender *Address `json:"sender"`
}

// RatesQuoteResponse — synthesized:RatesQuoteResponse.
type RatesQuoteResponse struct {
	Data []*RateQuote `json:"data"`

	AdditionalProperties map[string]any `json:"-"`
}

func (value *RatesQuoteResponse) UnmarshalJSON(data []byte) error {
	type plain RatesQuoteResponse
	var decoded plain
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	for _, key := range []string{"data"} {
		delete(fields, key)
	}
	decoded.AdditionalProperties = make(map[string]any, len(fields))
	for key, raw := range fields {
		var extra any
		if err := json.Unmarshal(raw, &extra); err != nil {
			return err
		}
		decoded.AdditionalProperties[key] = extra
	}
	*value = RatesQuoteResponse(decoded)
	return nil
}

func (value RatesQuoteResponse) MarshalJSON() ([]byte, error) {
	type plain RatesQuoteResponse
	data, err := json.Marshal(plain(value))
	if err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return nil, err
	}
	for key, extra := range value.AdditionalProperties {
		switch key {
		case "data":
			continue
		}
		raw, err := json.Marshal(extra)
		if err != nil {
			return nil, err
		}
		fields[key] = raw
	}
	return json.Marshal(fields)
}

// Shipment — #/components/schemas/Shipment.
type Shipment struct {
	CreatedAt string `json:"created_at"`

	DeliveryInstructions *string `json:"delivery_instructions,omitempty"`

	ID string `json:"id"`

	Metadata map[string]string `json:"metadata,omitempty"`

	// Allowed: "shipment".
	Object string `json:"object"`

	Parcels []*Parcel `json:"parcels"`

	Recipient *Address `json:"recipient"`

	Reference string `json:"reference"`

	Sender *Address `json:"sender"`

	// Allowed: "economy", "express", "same_day".
	Service string `json:"service"`

	Status ShipmentStatus `json:"status"`

	TrackingNumber string `json:"tracking_number"`

	UpdatedAt string `json:"updated_at"`
}

// ShipmentPage — #/components/schemas/ShipmentPage.
type ShipmentPage struct {
	Data []*Shipment `json:"data"`

	HasMore bool `json:"has_more"`

	NextCursor *string `json:"next_cursor"`
}

// ShipmentStatus — #/components/schemas/ShipmentStatus. Allowed: "draft", "label_purchased", "in_transit", "out_for_delivery", "delivered", "exception", "canceled".
type ShipmentStatus = string

// ShipmentStatusEvent — #/components/schemas/ShipmentStatusEvent.
type ShipmentStatusEvent struct {
	CreatedAt string `json:"created_at"`

	Data *ShipmentStatusEventData `json:"data"`

	ID string `json:"id"`

	// Allowed: "shipment.status_changed".
	Type string `json:"type"`
}

// ShipmentStatusEventData — synthesized:ShipmentStatusEventData.
type ShipmentStatusEventData struct {
	Event *TrackingEvent `json:"event"`

	Shipment *Shipment `json:"shipment"`
}

// TrackingEvent — #/components/schemas/TrackingEvent.
type TrackingEvent struct {
	ID string `json:"id"`

	Location *TrackingEventLocation `json:"location"`

	Message *string `json:"message,omitempty"`

	// Allowed: "tracking_event".
	Object string `json:"object"`

	OccurredAt string `json:"occurred_at"`

	ShipmentID string `json:"shipment_id"`

	Status ShipmentStatus `json:"status"`
}

// TrackingEventLocation — synthesized:TrackingEventLocation.
type TrackingEventLocation struct {
	City string `json:"city"`

	Country string `json:"country"`
}

// TrackingEventPage — #/components/schemas/TrackingEventPage.
type TrackingEventPage struct {
	Data []*TrackingEvent `json:"data"`

	HasMore bool `json:"has_more"`

	NextCursor *string `json:"next_cursor"`
}

// TrackingTimeline — #/components/schemas/TrackingTimeline.
type TrackingTimeline struct {
	Events []*TrackingEvent `json:"events"`

	Shipment *Shipment `json:"shipment"`
}

// UpdateShipmentRequest — #/components/schemas/UpdateShipmentRequest.
type UpdateShipmentRequest struct {
	DeliveryInstructions *string `json:"delivery_instructions,omitempty"`

	Metadata map[string]string `json:"metadata,omitempty"`
}

// UpdateWebhookEndpointRequest — #/components/schemas/UpdateWebhookEndpointRequest.
type UpdateWebhookEndpointRequest struct {
	Enabled *bool `json:"enabled,omitempty"`

	Events []WebhookEventType `json:"events,omitempty"`

	URL *string `json:"url,omitempty"`
}

// WebhookEndpoint — #/components/schemas/WebhookEndpoint.
type WebhookEndpoint struct {
	CreatedAt string `json:"created_at"`

	Enabled bool `json:"enabled"`

	Events []WebhookEventType `json:"events"`

	ID string `json:"id"`

	// Allowed: "webhook_endpoint".
	Object string `json:"object"`

	SigningSecretHint *string `json:"signing_secret_hint,omitempty"`

	URL string `json:"url"`
}

// WebhookEndpointPage — #/components/schemas/WebhookEndpointPage.
type WebhookEndpointPage struct {
	Data []*WebhookEndpoint `json:"data"`

	HasMore bool `json:"has_more"`

	NextCursor *string `json:"next_cursor"`
}

// WebhookEventType — #/components/schemas/WebhookEventType. Allowed: "shipment.created", "shipment.status_changed", "shipment.delivered", "shipment.exception", "pickup.completed".
type WebhookEventType = string
