// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

package parceleventsnightly

import (
	"context"

	"github.com/sdk-fixture-lab-260904/parcel-events-nightly-go/kernel"
)

// ShipmentsService is the `shipments` resource.
type ShipmentsService struct {
	core *core

	Events *ShipmentsEventsService
}

func newShipmentsService(c *core) *ShipmentsService {
	s := &ShipmentsService{core: c}
	s.Events = newShipmentsEventsService(c)
	return s
}

// Cancel — Cancel a shipment before handoff
//
// `DELETE /v1/shipments/{shipment_id}` (`cancelShipment`)
func (s *ShipmentsService) Cancel(ctx context.Context, shipmentID string, opts ...kernel.RequestOption) error {
	if err := s.core.kernel.ValidateValue(shipmentID, sdkContracts["shipments.cancel:path:shipment_id"], opts...); err != nil {
		return err
	}
	options := make([]kernel.RequestOption, 0, len(opts)+2)
	options = append(options, kernel.WithParameter("path", "shipment_id", shipmentID, kernel.ParameterSerialization{Style: "simple", Explode: false, AllowReserved: false, OmitNil: false}))
	options = append(options, opts...)
	_, err := s.core.do(ctx, "DELETE", "/v1/shipments/"+"{shipment_id}", options...)
	if err != nil {
		return err
	}
	return nil
}

// Create — Create a shipment
//
// `POST /v1/shipments` (`createShipment`)
func (s *ShipmentsService) Create(ctx context.Context, body CreateShipmentRequest, params ShipmentsCreateParams, opts ...kernel.RequestOption) (*Shipment, error) {
	if err := s.core.kernel.ValidateValue(params.IdempotencyKey, sdkContracts["shipments.create:header:Idempotency-Key"], opts...); err != nil {
		return nil, err
	}
	options := make([]kernel.RequestOption, 0, len(opts)+2)
	options = append(options, kernel.WithParameter("header", "Idempotency-Key", params.IdempotencyKey, kernel.ParameterSerialization{Style: "simple", Explode: false, AllowReserved: false, OmitNil: false}))
	options = append(options, kernel.WithJSONBody(body))
	options = append(options, kernel.WithBodyContract(sdkContracts["shipments.create:body"]))
	options = append(options, kernel.WithResponseContract(sdkContracts["shipments.create:response"]))
	options = append(options, opts...)
	response, err := s.core.do(ctx, "POST", "/v1/shipments", options...)
	if err != nil {
		return nil, err
	}
	out, err := decodeResponse[Shipment](response.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// List — List shipments (nightly run 20260910-b9ba2a4c)
//
// `GET /v1/shipments` (`listShipments`)
//
// Paginated (`cursor_page`): walk every item with the returned page's Pager.
func (s *ShipmentsService) List(ctx context.Context, params ShipmentsListParams, opts ...kernel.RequestOption) (*kernel.Page[Shipment], error) {
	if params.Cursor != nil {
		if err := s.core.kernel.ValidateValue(params.Cursor, sdkContracts["shipments.list:query:cursor"], opts...); err != nil {
			return nil, err
		}
	}
	if params.Limit != nil {
		if err := s.core.kernel.ValidateValue(params.Limit, sdkContracts["shipments.list:query:limit"], opts...); err != nil {
			return nil, err
		}
	}
	if params.Status != nil {
		if err := s.core.kernel.ValidateValue(params.Status, sdkContracts["shipments.list:query:status"], opts...); err != nil {
			return nil, err
		}
	}
	options := []kernel.RequestOption{kernel.WithResponseContract(sdkContracts["shipments.list:response"])}
	options = append(options, opts...)
	query := make([]kernel.QueryParam, 0, 3)
	query = append(query, kernel.QueryParam{Name: "cursor", Value: params.Cursor, Serialization: &kernel.ParameterSerialization{Style: "form", Explode: true, AllowReserved: false, OmitNil: true}})
	query = append(query, kernel.QueryParam{Name: "limit", Value: params.Limit, Serialization: &kernel.ParameterSerialization{Style: "form", Explode: true, AllowReserved: false, OmitNil: true}})
	query = append(query, kernel.QueryParam{Name: "status", Value: params.Status, Serialization: &kernel.ParameterSerialization{Style: "form", Explode: true, AllowReserved: false, OmitNil: true}})
	request := kernel.PageRequest{Method: "GET", Options: options, URL: "/v1/shipments", Query: query}
	scheme := kernel.CursorScheme{RequestCursor: "query.cursor", ResponseItems: "$.data", ResponseNextCursor: "$.next_cursor"}
	return kernel.FetchPage[Shipment](ctx, s.core, request, scheme)
}

// Retrieve — Retrieve a shipment
//
// `GET /v1/shipments/{shipment_id}` (`retrieveShipment`)
func (s *ShipmentsService) Retrieve(ctx context.Context, shipmentID string, opts ...kernel.RequestOption) (*Shipment, error) {
	if err := s.core.kernel.ValidateValue(shipmentID, sdkContracts["shipments.retrieve:path:shipment_id"], opts...); err != nil {
		return nil, err
	}
	options := make([]kernel.RequestOption, 0, len(opts)+2)
	options = append(options, kernel.WithParameter("path", "shipment_id", shipmentID, kernel.ParameterSerialization{Style: "simple", Explode: false, AllowReserved: false, OmitNil: false}))
	options = append(options, kernel.WithResponseContract(sdkContracts["shipments.retrieve:response"]))
	options = append(options, opts...)
	response, err := s.core.do(ctx, "GET", "/v1/shipments/"+"{shipment_id}", options...)
	if err != nil {
		return nil, err
	}
	out, err := decodeResponse[Shipment](response.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Update — Update delivery instructions
//
// `PATCH /v1/shipments/{shipment_id}` (`updateShipment`)
func (s *ShipmentsService) Update(ctx context.Context, shipmentID string, body UpdateShipmentRequest, opts ...kernel.RequestOption) (*Shipment, error) {
	if err := s.core.kernel.ValidateValue(shipmentID, sdkContracts["shipments.update:path:shipment_id"], opts...); err != nil {
		return nil, err
	}
	options := make([]kernel.RequestOption, 0, len(opts)+2)
	options = append(options, kernel.WithParameter("path", "shipment_id", shipmentID, kernel.ParameterSerialization{Style: "simple", Explode: false, AllowReserved: false, OmitNil: false}))
	options = append(options, kernel.WithJSONBody(body))
	options = append(options, kernel.WithBodyContract(sdkContracts["shipments.update:body"]))
	options = append(options, kernel.WithResponseContract(sdkContracts["shipments.update:response"]))
	options = append(options, opts...)
	response, err := s.core.do(ctx, "PATCH", "/v1/shipments/"+"{shipment_id}", options...)
	if err != nil {
		return nil, err
	}
	out, err := decodeResponse[Shipment](response.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ShipmentsCreateParams holds the query/header parameters of `shipments.create`.
type ShipmentsCreateParams struct {
	IdempotencyKey string
}

// ShipmentsListParams holds the query/header parameters of `shipments.list`.
type ShipmentsListParams struct {
	Cursor *string

	Limit *int64

	Status *ShipmentStatus
}
