// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

package parceleventsnightly

import (
	"context"

	"github.com/sdk-fixture-lab-260904/parcel-events-nightly-go/kernel"
)

// TrackingService is the `tracking` resource.
type TrackingService struct {
	core *core
}

func newTrackingService(c *core) *TrackingService {
	s := &TrackingService{core: c}
	return s
}

// Retrieve — Retrieve a public tracking timeline
//
// `GET /v1/tracking/{tracking_number}` (`retrieveTrackingTimeline`)
func (s *TrackingService) Retrieve(ctx context.Context, trackingNumber string, opts ...kernel.RequestOption) (*TrackingTimeline, error) {
	if err := s.core.kernel.ValidateValue(trackingNumber, sdkContracts["tracking.retrieve:path:tracking_number"], opts...); err != nil {
		return nil, err
	}
	options := make([]kernel.RequestOption, 0, len(opts)+2)
	options = append(options, kernel.WithParameter("path", "tracking_number", trackingNumber, kernel.ParameterSerialization{Style: "simple", Explode: false, AllowReserved: false, OmitNil: false}))
	options = append(options, kernel.WithResponseContract(sdkContracts["tracking.retrieve:response"]))
	options = append(options, opts...)
	response, err := s.core.do(ctx, "GET", "/v1/tracking/"+"{tracking_number}", options...)
	if err != nil {
		return nil, err
	}
	out, err := decodeResponse[TrackingTimeline](response.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
