// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

package parceleventsnightly

import (
	"context"

	"github.com/sdk-fixture-lab-260904/parcel-events-nightly-go/kernel"
)

// WebhookEndpointsService is the `webhook_endpoints` resource.
type WebhookEndpointsService struct {
	core *core
}

func newWebhookEndpointsService(c *core) *WebhookEndpointsService {
	s := &WebhookEndpointsService{core: c}
	return s
}

// Create — Register a webhook endpoint
//
// `POST /v1/webhook-endpoints` (`createWebhookEndpoint`)
func (s *WebhookEndpointsService) Create(ctx context.Context, body CreateWebhookEndpointRequest, opts ...kernel.RequestOption) (*WebhookEndpoint, error) {
	options := make([]kernel.RequestOption, 0, len(opts)+2)
	options = append(options, kernel.WithJSONBody(body))
	options = append(options, kernel.WithBodyContract(sdkContracts["webhook_endpoints.create:body"]))
	options = append(options, kernel.WithResponseContract(sdkContracts["webhook_endpoints.create:response"]))
	options = append(options, opts...)
	response, err := s.core.do(ctx, "POST", "/v1/webhook-endpoints", options...)
	if err != nil {
		return nil, err
	}
	out, err := decodeResponse[WebhookEndpoint](response.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// List — List webhook endpoints
//
// `GET /v1/webhook-endpoints` (`listWebhookEndpoints`)
//
// Paginated (`cursor_page`): walk every item with the returned page's Pager.
func (s *WebhookEndpointsService) List(ctx context.Context, params WebhookEndpointsListParams, opts ...kernel.RequestOption) (*kernel.Page[WebhookEndpoint], error) {
	if params.Cursor != nil {
		if err := s.core.kernel.ValidateValue(params.Cursor, sdkContracts["webhook_endpoints.list:query:cursor"], opts...); err != nil {
			return nil, err
		}
	}
	if params.Limit != nil {
		if err := s.core.kernel.ValidateValue(params.Limit, sdkContracts["webhook_endpoints.list:query:limit"], opts...); err != nil {
			return nil, err
		}
	}
	options := []kernel.RequestOption{kernel.WithResponseContract(sdkContracts["webhook_endpoints.list:response"])}
	options = append(options, opts...)
	query := make([]kernel.QueryParam, 0, 2)
	query = append(query, kernel.QueryParam{Name: "cursor", Value: params.Cursor, Serialization: &kernel.ParameterSerialization{Style: "form", Explode: true, AllowReserved: false, OmitNil: true}})
	query = append(query, kernel.QueryParam{Name: "limit", Value: params.Limit, Serialization: &kernel.ParameterSerialization{Style: "form", Explode: true, AllowReserved: false, OmitNil: true}})
	request := kernel.PageRequest{Method: "GET", Options: options, URL: "/v1/webhook-endpoints", Query: query}
	scheme := kernel.CursorScheme{RequestCursor: "query.cursor", ResponseItems: "$.data", ResponseNextCursor: "$.next_cursor"}
	return kernel.FetchPage[WebhookEndpoint](ctx, s.core, request, scheme)
}

// Remove — Delete a webhook endpoint
//
// `DELETE /v1/webhook-endpoints/{endpoint_id}` (`deleteWebhookEndpoint`)
func (s *WebhookEndpointsService) Remove(ctx context.Context, endpointID string, opts ...kernel.RequestOption) error {
	if err := s.core.kernel.ValidateValue(endpointID, sdkContracts["webhook_endpoints.remove:path:endpoint_id"], opts...); err != nil {
		return err
	}
	options := make([]kernel.RequestOption, 0, len(opts)+2)
	options = append(options, kernel.WithParameter("path", "endpoint_id", endpointID, kernel.ParameterSerialization{Style: "simple", Explode: false, AllowReserved: false, OmitNil: false}))
	options = append(options, opts...)
	_, err := s.core.do(ctx, "DELETE", "/v1/webhook-endpoints/"+"{endpoint_id}", options...)
	if err != nil {
		return err
	}
	return nil
}

// Update — Update a webhook endpoint
//
// `PATCH /v1/webhook-endpoints/{endpoint_id}` (`updateWebhookEndpoint`)
func (s *WebhookEndpointsService) Update(ctx context.Context, endpointID string, body UpdateWebhookEndpointRequest, opts ...kernel.RequestOption) (*WebhookEndpoint, error) {
	if err := s.core.kernel.ValidateValue(endpointID, sdkContracts["webhook_endpoints.update:path:endpoint_id"], opts...); err != nil {
		return nil, err
	}
	options := make([]kernel.RequestOption, 0, len(opts)+2)
	options = append(options, kernel.WithParameter("path", "endpoint_id", endpointID, kernel.ParameterSerialization{Style: "simple", Explode: false, AllowReserved: false, OmitNil: false}))
	options = append(options, kernel.WithJSONBody(body))
	options = append(options, kernel.WithBodyContract(sdkContracts["webhook_endpoints.update:body"]))
	options = append(options, kernel.WithResponseContract(sdkContracts["webhook_endpoints.update:response"]))
	options = append(options, opts...)
	response, err := s.core.do(ctx, "PATCH", "/v1/webhook-endpoints/"+"{endpoint_id}", options...)
	if err != nil {
		return nil, err
	}
	out, err := decodeResponse[WebhookEndpoint](response.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// WebhookEndpointsListParams holds the query/header parameters of `webhook_endpoints.list`.
type WebhookEndpointsListParams struct {
	Cursor *string

	Limit *int64
}
