// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

package parceleventsnightly

import (
	"context"

	"github.com/sdk-fixture-lab-260904/parcel-events-nightly-go/kernel"
)

// RatesService is the `rates` resource.
type RatesService struct {
	core *core
}

func newRatesService(c *core) *RatesService {
	s := &RatesService{core: c}
	return s
}

// Quote — Quote available shipping services
//
// `POST /v1/rates/quote` (`quoteRates`)
func (s *RatesService) Quote(ctx context.Context, body RateQuoteRequest, opts ...kernel.RequestOption) (*RatesQuoteResponse, error) {
	options := make([]kernel.RequestOption, 0, len(opts)+2)
	options = append(options, kernel.WithJSONBody(body))
	options = append(options, kernel.WithBodyContract(sdkContracts["rates.quote:body"]))
	options = append(options, kernel.WithResponseContract(sdkContracts["rates.quote:response"]))
	options = append(options, opts...)
	response, err := s.core.do(ctx, "POST", "/v1/rates/quote", options...)
	if err != nil {
		return nil, err
	}
	out, err := decodeResponse[RatesQuoteResponse](response.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
