// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

package parceleventsnightly

import (
	"context"

	"github.com/sdk-fixture-lab-260904/parcel-events-nightly-go/kernel"
)

// ShipmentsEventsService is the `shipments.events` resource.
type ShipmentsEventsService struct {
	core *core
}

func newShipmentsEventsService(c *core) *ShipmentsEventsService {
	s := &ShipmentsEventsService{core: c}
	return s
}

// List — List tracking events for a shipment
//
// `GET /v1/shipments/{shipment_id}/events` (`listShipmentEvents`)
//
// Paginated (`cursor_page`): walk every item with the returned page's Pager.
func (s *ShipmentsEventsService) List(ctx context.Context, shipmentID string, params ShipmentsEventsListParams, opts ...kernel.RequestOption) (*kernel.Page[TrackingEvent], error) {
	if err := s.core.kernel.ValidateValue(shipmentID, sdkContracts["shipments.events.list:path:shipment_id"], opts...); err != nil {
		return nil, err
	}
	if params.Cursor != nil {
		if err := s.core.kernel.ValidateValue(params.Cursor, sdkContracts["shipments.events.list:query:cursor"], opts...); err != nil {
			return nil, err
		}
	}
	if params.Limit != nil {
		if err := s.core.kernel.ValidateValue(params.Limit, sdkContracts["shipments.events.list:query:limit"], opts...); err != nil {
			return nil, err
		}
	}
	options := []kernel.RequestOption{kernel.WithResponseContract(sdkContracts["shipments.events.list:response"])}
	options = append(options, kernel.WithParameter("path", "shipment_id", shipmentID, kernel.ParameterSerialization{Style: "simple", Explode: false, AllowReserved: false, OmitNil: false}))
	options = append(options, opts...)
	query := make([]kernel.QueryParam, 0, 2)
	query = append(query, kernel.QueryParam{Name: "cursor", Value: params.Cursor, Serialization: &kernel.ParameterSerialization{Style: "form", Explode: true, AllowReserved: false, OmitNil: true}})
	query = append(query, kernel.QueryParam{Name: "limit", Value: params.Limit, Serialization: &kernel.ParameterSerialization{Style: "form", Explode: true, AllowReserved: false, OmitNil: true}})
	request := kernel.PageRequest{Method: "GET", Options: options, URL: "/v1/shipments/" + "{shipment_id}" + "/events", Query: query}
	scheme := kernel.CursorScheme{RequestCursor: "query.cursor", ResponseItems: "$.data", ResponseNextCursor: "$.next_cursor"}
	return kernel.FetchPage[TrackingEvent](ctx, s.core, request, scheme)
}

// ShipmentsEventsListParams holds the query/header parameters of `shipments.events.list`.
type ShipmentsEventsListParams struct {
	Cursor *string

	Limit *int64
}
