// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

package parceleventsnightly

import (
	"context"

	"github.com/sdk-fixture-lab-260904/parcel-events-nightly-go/kernel"
)

// LabelsService is the `labels` resource.
type LabelsService struct {
	core *core
}

func newLabelsService(c *core) *LabelsService {
	s := &LabelsService{core: c}
	return s
}

// Create — Buy and render a shipping label
//
// `POST /v1/labels` (`createLabel`)
func (s *LabelsService) Create(ctx context.Context, body CreateLabelRequest, params LabelsCreateParams, opts ...kernel.RequestOption) (*Label, error) {
	if err := s.core.kernel.ValidateValue(params.IdempotencyKey, sdkContracts["labels.create:header:Idempotency-Key"], opts...); err != nil {
		return nil, err
	}
	options := make([]kernel.RequestOption, 0, len(opts)+2)
	options = append(options, kernel.WithParameter("header", "Idempotency-Key", params.IdempotencyKey, kernel.ParameterSerialization{Style: "simple", Explode: false, AllowReserved: false, OmitNil: false}))
	options = append(options, kernel.WithJSONBody(body))
	options = append(options, kernel.WithBodyContract(sdkContracts["labels.create:body"]))
	options = append(options, kernel.WithResponseContract(sdkContracts["labels.create:response"]))
	options = append(options, opts...)
	response, err := s.core.do(ctx, "POST", "/v1/labels", options...)
	if err != nil {
		return nil, err
	}
	out, err := decodeResponse[Label](response.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Retrieve — Retrieve label metadata and download URL
//
// `GET /v1/labels/{label_id}` (`retrieveLabel`)
func (s *LabelsService) Retrieve(ctx context.Context, labelID string, opts ...kernel.RequestOption) (*Label, error) {
	if err := s.core.kernel.ValidateValue(labelID, sdkContracts["labels.retrieve:path:label_id"], opts...); err != nil {
		return nil, err
	}
	options := make([]kernel.RequestOption, 0, len(opts)+2)
	options = append(options, kernel.WithParameter("path", "label_id", labelID, kernel.ParameterSerialization{Style: "simple", Explode: false, AllowReserved: false, OmitNil: false}))
	options = append(options, kernel.WithResponseContract(sdkContracts["labels.retrieve:response"]))
	options = append(options, opts...)
	response, err := s.core.do(ctx, "GET", "/v1/labels/"+"{label_id}", options...)
	if err != nil {
		return nil, err
	}
	out, err := decodeResponse[Label](response.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LabelsCreateParams holds the query/header parameters of `labels.create`.
type LabelsCreateParams struct {
	IdempotencyKey string
}
