// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

package parceleventsnightly

import (
	"context"

	"github.com/sdk-fixture-lab-260904/parcel-events-nightly-go/kernel"
)

// PickupsService is the `pickups` resource.
type PickupsService struct {
	core *core
}

func newPickupsService(c *core) *PickupsService {
	s := &PickupsService{core: c}
	return s
}

// Cancel — Cancel a pickup
//
// `DELETE /v1/pickups/{pickup_id}` (`cancelPickup`)
func (s *PickupsService) Cancel(ctx context.Context, pickupID string, opts ...kernel.RequestOption) error {
	if err := s.core.kernel.ValidateValue(pickupID, sdkContracts["pickups.cancel:path:pickup_id"], opts...); err != nil {
		return err
	}
	options := make([]kernel.RequestOption, 0, len(opts)+2)
	options = append(options, kernel.WithParameter("path", "pickup_id", pickupID, kernel.ParameterSerialization{Style: "simple", Explode: false, AllowReserved: false, OmitNil: false}))
	options = append(options, opts...)
	_, err := s.core.do(ctx, "DELETE", "/v1/pickups/"+"{pickup_id}", options...)
	if err != nil {
		return err
	}
	return nil
}

// Create — Schedule a carrier pickup
//
// `POST /v1/pickups` (`createPickup`)
func (s *PickupsService) Create(ctx context.Context, body CreatePickupRequest, params PickupsCreateParams, opts ...kernel.RequestOption) (*Pickup, error) {
	if err := s.core.kernel.ValidateValue(params.IdempotencyKey, sdkContracts["pickups.create:header:Idempotency-Key"], opts...); err != nil {
		return nil, err
	}
	options := make([]kernel.RequestOption, 0, len(opts)+2)
	options = append(options, kernel.WithParameter("header", "Idempotency-Key", params.IdempotencyKey, kernel.ParameterSerialization{Style: "simple", Explode: false, AllowReserved: false, OmitNil: false}))
	options = append(options, kernel.WithJSONBody(body))
	options = append(options, kernel.WithBodyContract(sdkContracts["pickups.create:body"]))
	options = append(options, kernel.WithResponseContract(sdkContracts["pickups.create:response"]))
	options = append(options, opts...)
	response, err := s.core.do(ctx, "POST", "/v1/pickups", options...)
	if err != nil {
		return nil, err
	}
	out, err := decodeResponse[Pickup](response.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// List — List scheduled pickups
//
// `GET /v1/pickups` (`listPickups`)
//
// Paginated (`cursor_page`): walk every item with the returned page's Pager.
func (s *PickupsService) List(ctx context.Context, params PickupsListParams, opts ...kernel.RequestOption) (*kernel.Page[Pickup], error) {
	if params.Cursor != nil {
		if err := s.core.kernel.ValidateValue(params.Cursor, sdkContracts["pickups.list:query:cursor"], opts...); err != nil {
			return nil, err
		}
	}
	if params.Limit != nil {
		if err := s.core.kernel.ValidateValue(params.Limit, sdkContracts["pickups.list:query:limit"], opts...); err != nil {
			return nil, err
		}
	}
	if params.ScheduledOn != nil {
		if err := s.core.kernel.ValidateValue(params.ScheduledOn, sdkContracts["pickups.list:query:scheduled_on"], opts...); err != nil {
			return nil, err
		}
	}
	options := []kernel.RequestOption{kernel.WithResponseContract(sdkContracts["pickups.list:response"])}
	options = append(options, opts...)
	query := make([]kernel.QueryParam, 0, 3)
	query = append(query, kernel.QueryParam{Name: "cursor", Value: params.Cursor, Serialization: &kernel.ParameterSerialization{Style: "form", Explode: true, AllowReserved: false, OmitNil: true}})
	query = append(query, kernel.QueryParam{Name: "limit", Value: params.Limit, Serialization: &kernel.ParameterSerialization{Style: "form", Explode: true, AllowReserved: false, OmitNil: true}})
	query = append(query, kernel.QueryParam{Name: "scheduled_on", Value: params.ScheduledOn, Serialization: &kernel.ParameterSerialization{Style: "form", Explode: true, AllowReserved: false, OmitNil: true}})
	request := kernel.PageRequest{Method: "GET", Options: options, URL: "/v1/pickups", Query: query}
	scheme := kernel.CursorScheme{RequestCursor: "query.cursor", ResponseItems: "$.data", ResponseNextCursor: "$.next_cursor"}
	return kernel.FetchPage[Pickup](ctx, s.core, request, scheme)
}

// Retrieve — Retrieve a pickup
//
// `GET /v1/pickups/{pickup_id}` (`retrievePickup`)
func (s *PickupsService) Retrieve(ctx context.Context, pickupID string, opts ...kernel.RequestOption) (*Pickup, error) {
	if err := s.core.kernel.ValidateValue(pickupID, sdkContracts["pickups.retrieve:path:pickup_id"], opts...); err != nil {
		return nil, err
	}
	options := make([]kernel.RequestOption, 0, len(opts)+2)
	options = append(options, kernel.WithParameter("path", "pickup_id", pickupID, kernel.ParameterSerialization{Style: "simple", Explode: false, AllowReserved: false, OmitNil: false}))
	options = append(options, kernel.WithResponseContract(sdkContracts["pickups.retrieve:response"]))
	options = append(options, opts...)
	response, err := s.core.do(ctx, "GET", "/v1/pickups/"+"{pickup_id}", options...)
	if err != nil {
		return nil, err
	}
	out, err := decodeResponse[Pickup](response.Data)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PickupsCreateParams holds the query/header parameters of `pickups.create`.
type PickupsCreateParams struct {
	IdempotencyKey string
}

// PickupsListParams holds the query/header parameters of `pickups.list`.
type PickupsListParams struct {
	Cursor *string

	Limit *int64

	ScheduledOn *string
}
