// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

// Generated smoke suite — one method per resource over httptest.Server.
package parceleventsnightly

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"reflect"
	"sync/atomic"
	"testing"
)

func TestLabelsCreate(t *testing.T) {
	var calls int32
	ctx := context.Background()
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		atomic.AddInt32(&calls, 1)
		if r.Method != "POST" {
			t.Errorf("method = %s, want POST", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(201)
		_, _ = w.Write([]byte("{\"download_url\":\"https://downloads.parcel-events.example/labels/synthetic-label.pdf\",\"expires_at\":\"2026-06-09T00:00:00Z\",\"format\":\"pdf\",\"id\":\"lbl_00000000000000000001\",\"object\":\"label\",\"price\":{\"amount\":\"12.50\",\"currency\":\"XTS\"},\"shipment_id\":\"shp_00000000000000000001\"}"))
	}))
	defer server.Close()
	client := NewClient(WithAPIKey("my-api-key"), WithBaseURL(server.URL))
	var body CreateLabelRequest
	if err := json.Unmarshal([]byte("{\"format\":\"pdf\",\"page_size\":\"four_by_six\",\"shipment_id\":\"shp_00000000000000000001\"}"), &body); err != nil {
		t.Fatalf("decode body: %v", err)
	}
	result, err := client.Labels.Create(ctx, body, LabelsCreateParams{IdempotencyKey: "123e4567-e89b-12d3-a456-426614174000"})
	if err != nil {
		t.Fatalf("call: %v", err)
	}
	if got := atomic.LoadInt32(&calls); got != 1 {
		t.Fatalf("calls = %d, want 1", got)
	}
	var want Label
	if err := json.Unmarshal([]byte("{\"download_url\":\"https://downloads.parcel-events.example/labels/synthetic-label.pdf\",\"expires_at\":\"2026-06-09T00:00:00Z\",\"format\":\"pdf\",\"id\":\"lbl_00000000000000000001\",\"object\":\"label\",\"price\":{\"amount\":\"12.50\",\"currency\":\"XTS\"},\"shipment_id\":\"shp_00000000000000000001\"}"), &want); err != nil {
		t.Fatalf("decode want: %v", err)
	}
	if !reflect.DeepEqual(*result, want) {
		t.Errorf("result = %#v, want %#v", *result, want)
	}
}

func TestPickupsCancel(t *testing.T) {
	var calls int32
	ctx := context.Background()
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		atomic.AddInt32(&calls, 1)
		if r.Method != "DELETE" {
			t.Errorf("method = %s, want DELETE", r.Method)
		}
		w.WriteHeader(204)
	}))
	defer server.Close()
	client := NewClient(WithAPIKey("my-api-key"), WithBaseURL(server.URL))
	if err := client.Pickups.Cancel(ctx, "pku_00000000000000000000"); err != nil {
		t.Fatalf("call: %v", err)
	}
	if got := atomic.LoadInt32(&calls); got != 1 {
		t.Fatalf("calls = %d, want 1", got)
	}
}

func TestRatesQuote(t *testing.T) {
	var calls int32
	ctx := context.Background()
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		atomic.AddInt32(&calls, 1)
		if r.Method != "POST" {
			t.Errorf("method = %s, want POST", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		_, _ = w.Write([]byte("{\"data\":[{\"amount\":{\"amount\":\"0.00\",\"currency\":\"AAA\"},\"carrier\":\"string\",\"estimated_delivery_date\":\"2024-01-01\",\"expires_at\":\"2024-01-01T00:00:00Z\",\"id\":\"string\",\"service\":\"string\"}]}"))
	}))
	defer server.Close()
	client := NewClient(WithAPIKey("my-api-key"), WithBaseURL(server.URL))
	var body RateQuoteRequest
	if err := json.Unmarshal([]byte("{\"parcels\":[{\"contents\":[{\"customs_code\":\"610910\",\"description\":\"Synthetic cotton shirt\",\"quantity\":2,\"unit_value\":{\"amount\":\"12.50\",\"currency\":\"XTS\"}}],\"height_cm\":12,\"length_cm\":30.5,\"weight_grams\":1750,\"width_cm\":20}],\"recipient\":{\"city\":\"Exampleton\",\"company\":\"Northstar Supplies\",\"country\":\"ZZ\",\"line1\":\"14 Fictional Quay\",\"line2\":\"Unit 7\",\"name\":\"Rowan Example\",\"phone\":\"+00000000000\",\"postal_code\":\"EX4 2PL\",\"region\":\"Test Province\"},\"sender\":{\"city\":\"Exampleton\",\"company\":\"Northstar Supplies\",\"country\":\"ZZ\",\"line1\":\"14 Fictional Quay\",\"line2\":\"Unit 7\",\"name\":\"Rowan Example\",\"phone\":\"+00000000000\",\"postal_code\":\"EX4 2PL\",\"region\":\"Test Province\"}}"), &body); err != nil {
		t.Fatalf("decode body: %v", err)
	}
	result, err := client.Rates.Quote(ctx, body)
	if err != nil {
		t.Fatalf("call: %v", err)
	}
	if got := atomic.LoadInt32(&calls); got != 1 {
		t.Fatalf("calls = %d, want 1", got)
	}
	var want RatesQuoteResponse
	if err := json.Unmarshal([]byte("{\"data\":[{\"amount\":{\"amount\":\"0.00\",\"currency\":\"AAA\"},\"carrier\":\"string\",\"estimated_delivery_date\":\"2024-01-01\",\"expires_at\":\"2024-01-01T00:00:00Z\",\"id\":\"string\",\"service\":\"string\"}]}"), &want); err != nil {
		t.Fatalf("decode want: %v", err)
	}
	if !reflect.DeepEqual(*result, want) {
		t.Errorf("result = %#v, want %#v", *result, want)
	}
}

func TestShipmentsCancel(t *testing.T) {
	var calls int32
	ctx := context.Background()
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		atomic.AddInt32(&calls, 1)
		if r.Method != "DELETE" {
			t.Errorf("method = %s, want DELETE", r.Method)
		}
		w.WriteHeader(204)
	}))
	defer server.Close()
	client := NewClient(WithAPIKey("my-api-key"), WithBaseURL(server.URL))
	if err := client.Shipments.Cancel(ctx, "shp_00000000000000000000"); err != nil {
		t.Fatalf("call: %v", err)
	}
	if got := atomic.LoadInt32(&calls); got != 1 {
		t.Fatalf("calls = %d, want 1", got)
	}
}

func TestShipmentsEventsList(t *testing.T) {
	var calls int32
	ctx := context.Background()
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		atomic.AddInt32(&calls, 1)
		if r.Method != "GET" {
			t.Errorf("method = %s, want GET", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		_, _ = w.Write([]byte("{\"data\":[{\"id\":\"evt_00000000000000000001\",\"location\":{\"city\":\"Samplehaven\",\"country\":\"ZZ\"},\"message\":\"Parcel scanned at synthetic sorting hub\",\"object\":\"tracking_event\",\"occurred_at\":\"2026-09-05T05:40:00Z\",\"shipment_id\":\"shp_00000000000000000001\",\"status\":\"canceled\"}],\"has_more\":true,\"next_cursor\":\"string\"}"))
	}))
	defer server.Close()
	client := NewClient(WithAPIKey("my-api-key"), WithBaseURL(server.URL))
	result, err := client.Shipments.Events.List(ctx, "shp_00000000000000000000", ShipmentsEventsListParams{})
	if err != nil {
		t.Fatalf("call: %v", err)
	}
	if got := atomic.LoadInt32(&calls); got != 1 {
		t.Fatalf("calls = %d, want 1", got)
	}
	items, err := result.Items()
	if err != nil {
		t.Fatalf("items: %v", err)
	}
	if items == nil {
		t.Fatalf("items = nil, want a decoded list")
	}
}

func TestTrackingRetrieve(t *testing.T) {
	var calls int32
	ctx := context.Background()
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		atomic.AddInt32(&calls, 1)
		if r.Method != "GET" {
			t.Errorf("method = %s, want GET", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		_, _ = w.Write([]byte("{\"events\":[{\"id\":\"evt_00000000000000000001\",\"location\":{\"city\":\"Samplehaven\",\"country\":\"ZZ\"},\"message\":\"Parcel scanned at synthetic sorting hub\",\"object\":\"tracking_event\",\"occurred_at\":\"2026-09-05T05:40:00Z\",\"shipment_id\":\"shp_00000000000000000001\",\"status\":\"canceled\"}],\"shipment\":{\"created_at\":\"2026-09-04T08:15:30Z\",\"delivery_instructions\":\"string\",\"id\":\"shp_00000000000000000001\",\"metadata\":{\"additionalProp1\":\"string\"},\"object\":\"shipment\",\"parcels\":[{\"contents\":[{\"customs_code\":\"610910\",\"description\":\"Synthetic cotton shirt\",\"quantity\":2,\"unit_value\":{\"amount\":\"12.50\",\"currency\":\"XTS\"}}],\"height_cm\":12,\"length_cm\":30.5,\"weight_grams\":1750,\"width_cm\":20}],\"recipient\":{\"city\":\"Exampleton\",\"company\":\"Northstar Supplies\",\"country\":\"ZZ\",\"line1\":\"14 Fictional Quay\",\"line2\":\"Unit 7\",\"name\":\"Rowan Example\",\"phone\":\"+00000000000\",\"postal_code\":\"EX4 2PL\",\"region\":\"Test Province\"},\"reference\":\"synthetic-order-1042\",\"sender\":{\"city\":\"Exampleton\",\"company\":\"Northstar Supplies\",\"country\":\"ZZ\",\"line1\":\"14 Fictional Quay\",\"line2\":\"Unit 7\",\"name\":\"Rowan Example\",\"phone\":\"+00000000000\",\"postal_code\":\"EX4 2PL\",\"region\":\"Test Province\"},\"service\":\"economy\",\"status\":\"canceled\",\"tracking_number\":\"PE-000000000001\",\"updated_at\":\"2026-09-04T08:16:12Z\"}}"))
	}))
	defer server.Close()
	client := NewClient(WithAPIKey("my-api-key"), WithBaseURL(server.URL))
	result, err := client.Tracking.Retrieve(ctx, "PE-000000000000")
	if err != nil {
		t.Fatalf("call: %v", err)
	}
	if got := atomic.LoadInt32(&calls); got != 1 {
		t.Fatalf("calls = %d, want 1", got)
	}
	var want TrackingTimeline
	if err := json.Unmarshal([]byte("{\"events\":[{\"id\":\"evt_00000000000000000001\",\"location\":{\"city\":\"Samplehaven\",\"country\":\"ZZ\"},\"message\":\"Parcel scanned at synthetic sorting hub\",\"object\":\"tracking_event\",\"occurred_at\":\"2026-09-05T05:40:00Z\",\"shipment_id\":\"shp_00000000000000000001\",\"status\":\"canceled\"}],\"shipment\":{\"created_at\":\"2026-09-04T08:15:30Z\",\"delivery_instructions\":\"string\",\"id\":\"shp_00000000000000000001\",\"metadata\":{\"additionalProp1\":\"string\"},\"object\":\"shipment\",\"parcels\":[{\"contents\":[{\"customs_code\":\"610910\",\"description\":\"Synthetic cotton shirt\",\"quantity\":2,\"unit_value\":{\"amount\":\"12.50\",\"currency\":\"XTS\"}}],\"height_cm\":12,\"length_cm\":30.5,\"weight_grams\":1750,\"width_cm\":20}],\"recipient\":{\"city\":\"Exampleton\",\"company\":\"Northstar Supplies\",\"country\":\"ZZ\",\"line1\":\"14 Fictional Quay\",\"line2\":\"Unit 7\",\"name\":\"Rowan Example\",\"phone\":\"+00000000000\",\"postal_code\":\"EX4 2PL\",\"region\":\"Test Province\"},\"reference\":\"synthetic-order-1042\",\"sender\":{\"city\":\"Exampleton\",\"company\":\"Northstar Supplies\",\"country\":\"ZZ\",\"line1\":\"14 Fictional Quay\",\"line2\":\"Unit 7\",\"name\":\"Rowan Example\",\"phone\":\"+00000000000\",\"postal_code\":\"EX4 2PL\",\"region\":\"Test Province\"},\"service\":\"economy\",\"status\":\"canceled\",\"tracking_number\":\"PE-000000000001\",\"updated_at\":\"2026-09-04T08:16:12Z\"}}"), &want); err != nil {
		t.Fatalf("decode want: %v", err)
	}
	if !reflect.DeepEqual(*result, want) {
		t.Errorf("result = %#v, want %#v", *result, want)
	}
}

func TestWebhookEndpointsCreate(t *testing.T) {
	var calls int32
	ctx := context.Background()
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		atomic.AddInt32(&calls, 1)
		if r.Method != "POST" {
			t.Errorf("method = %s, want POST", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(201)
		_, _ = w.Write([]byte("{\"created_at\":\"2026-06-09T00:00:00Z\",\"enabled\":true,\"events\":[\"pickup.completed\"],\"id\":\"whe_00000000000000000001\",\"object\":\"webhook_endpoint\",\"signing_secret_hint\":\"synthetic-key-ending-0000\",\"url\":\"https://hooks.parcel-events.example/events\"}"))
	}))
	defer server.Close()
	client := NewClient(WithAPIKey("my-api-key"), WithBaseURL(server.URL))
	var body CreateWebhookEndpointRequest
	if err := json.Unmarshal([]byte("{\"description\":\"string\",\"events\":[\"pickup.completed\"],\"url\":\"https://hooks.parcel-events.example/events\"}"), &body); err != nil {
		t.Fatalf("decode body: %v", err)
	}
	result, err := client.WebhookEndpoints.Create(ctx, body)
	if err != nil {
		t.Fatalf("call: %v", err)
	}
	if got := atomic.LoadInt32(&calls); got != 1 {
		t.Fatalf("calls = %d, want 1", got)
	}
	var want WebhookEndpoint
	if err := json.Unmarshal([]byte("{\"created_at\":\"2026-06-09T00:00:00Z\",\"enabled\":true,\"events\":[\"pickup.completed\"],\"id\":\"whe_00000000000000000001\",\"object\":\"webhook_endpoint\",\"signing_secret_hint\":\"synthetic-key-ending-0000\",\"url\":\"https://hooks.parcel-events.example/events\"}"), &want); err != nil {
		t.Fatalf("decode want: %v", err)
	}
	if !reflect.DeepEqual(*result, want) {
		t.Errorf("result = %#v, want %#v", *result, want)
	}
}
