// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

// Run with: go run ./examples/shipments
package main

import (
	"context"
	"fmt"

	parceleventsnightly "github.com/sdk-fixture-lab-260904/parcel-events-nightly-go"
)

func main() {
	ctx := context.Background()
	client := parceleventsnightly.NewClient(parceleventsnightly.WithAPIKey("my-api-key"))
	if err := client.Shipments.Cancel(ctx, "shp_00000000000000000000"); err != nil {
		panic(err)
	}
	fmt.Println("ok")
}
