// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

// Run with: go run ./examples/labels
package main

import (
	"context"
	"encoding/json"
	"fmt"

	parceleventsnightly "github.com/sdk-fixture-lab-260904/parcel-events-nightly-go"
)

func main() {
	ctx := context.Background()
	client := parceleventsnightly.NewClient(parceleventsnightly.WithAPIKey("my-api-key"))

	var body parceleventsnightly.CreateLabelRequest
	if err := json.Unmarshal([]byte("{\"format\":\"pdf\",\"page_size\":\"four_by_six\",\"shipment_id\":\"shp_00000000000000000001\"}"), &body); err != nil {
		panic(err)
	}
	result, err := client.Labels.Create(ctx, body, parceleventsnightly.LabelsCreateParams{IdempotencyKey: "123e4567-e89b-12d3-a456-426614174000"})
	if err != nil {
		panic(err)
	}
	fmt.Println(result)
}
