// Code generated by @doctorine/sdk-codegen (Doctorine SDK Foundry). DO NOT EDIT.

// Run with: go run ./examples/rates
package main

import (
	"context"
	"encoding/json"
	"fmt"

	parceleventsnightly "github.com/sdk-fixture-lab-260904/parcel-events-nightly-go"
)

func main() {
	ctx := context.Background()
	client := parceleventsnightly.NewClient(parceleventsnightly.WithAPIKey("my-api-key"))

	var body parceleventsnightly.RateQuoteRequest
	if err := json.Unmarshal([]byte("{\"parcels\":[{\"contents\":[{\"customs_code\":\"610910\",\"description\":\"Synthetic cotton shirt\",\"quantity\":2,\"unit_value\":{\"amount\":\"12.50\",\"currency\":\"XTS\"}}],\"height_cm\":12,\"length_cm\":30.5,\"weight_grams\":1750,\"width_cm\":20}],\"recipient\":{\"city\":\"Exampleton\",\"company\":\"Northstar Supplies\",\"country\":\"ZZ\",\"line1\":\"14 Fictional Quay\",\"line2\":\"Unit 7\",\"name\":\"Rowan Example\",\"phone\":\"+00000000000\",\"postal_code\":\"EX4 2PL\",\"region\":\"Test Province\"},\"sender\":{\"city\":\"Exampleton\",\"company\":\"Northstar Supplies\",\"country\":\"ZZ\",\"line1\":\"14 Fictional Quay\",\"line2\":\"Unit 7\",\"name\":\"Rowan Example\",\"phone\":\"+00000000000\",\"postal_code\":\"EX4 2PL\",\"region\":\"Test Province\"}}"), &body); err != nil {
		panic(err)
	}
	result, err := client.Rates.Quote(ctx, body)
	if err != nil {
		panic(err)
	}
	fmt.Println(result)
}
